// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 RadsammyT <32146976+RadsammyT@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 SX_7 <sn1.test.preria.2002@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared.Popups;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
using Content.Shared._EstacaoPirata.Cards.Card;
using Content.Shared._EstacaoPirata.Cards.Stack;

namespace Content.Client._EstacaoPirata.Cards.Hand.UI;

[GenerateTypedNameReferences]
public sealed partial class CardHandMenu : RadialMenu
{
    [Dependency] private readonly EntityManager _entManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly SharedPopupSystem _popup;

    public event Action<NetEntity>? CardHandDrawMessageAction;

    private EntityUid _owner;

    /// <summary>
    /// Constructs the card-hand radial menu for the given owner entity, creating one radial button per card in the owner's CardStackComponent.
    /// </summary>
    /// <param name="owner">EntityUid of the card stack owner whose cards will be displayed.</param>
    /// <param name="bui">The bound user interface used to forward selected-card draw messages.</param>
    /// <remarks>
    /// For each card in the owner's CardStackComponent this constructor:
    /// - Determines a display name (uses metadata.EntityName when the card is flipped and metadata is present; otherwise localizes CardComponent.Name).
    /// - Creates a 64×64 radial button with that tooltip and, if available, a scaled sprite icon child.
    /// - Wires the button to emit a NetEntity for the selected card via CardHandDrawMessageAction and close the menu on release.
    /// Finally, it subscribes CardHandDrawMessageAction to <paramref name="bui"/>.SendCardHandDrawMessage.
    /// If required components (CardStackComponent, CardComponent) or a local session are missing, the constructor returns early and no UI is built.
    /// </remarks>
    public CardHandMenu(EntityUid owner, CardHandMenuBoundUserInterface bui)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _spriteSystem = _entManager.System<SpriteSystem>();
        _popup = _entManager.System<SharedPopupSystem>();

        _owner = owner;

        // Find the main radial container
        var main = FindControl<RadialContainer>("Main");

        if (!_entManager.TryGetComponent<CardStackComponent>(owner, out var stack))
            return;

        foreach (var card in stack.Cards)
        {
            if (_playerManager.LocalSession == null)
                return;
            if (!_entManager.TryGetComponent<CardComponent>(card, out var cardComp))
                return;
            string cardName;
            if (cardComp.Flipped && _entManager.TryGetComponent<MetaDataComponent>(card, out var metadata))
            {
                cardName = metadata.EntityName;
            }
            else
            {
                cardName = Loc.GetString(cardComp.Name);
            }

            var button = new CardMenuButton()
            {
                StyleClasses = { "RadialMenuButton" },
                SetSize = new Vector2(64f, 64f),
                ToolTip = cardName,
            };

            if (_entManager.TryGetComponent<SpriteComponent>(card, out var sprite))
            {
                if (sprite.Icon == null)
                    continue;

                var tex = new TextureRect()
                {
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Texture = sprite.Icon?.Default,
                    TextureScale = new Vector2(2f, 2f),
                };

                button.AddChild(tex);
            }

            main.AddChild(button);

            button.OnButtonUp += _ =>
            {
                CardHandDrawMessageAction?.Invoke(_entManager.GetNetEntity(card));
                Close();
            };
        }

        CardHandDrawMessageAction += bui.SendCardHandDrawMessage;
    }
}

public sealed class CardMenuButton : RadialMenuTextureButton
{
    /// <summary>
    /// Initializes a new instance of the <see cref="CardMenuButton"/> class.
    /// </summary>
    /// <remarks>
    /// A simple specialized radial texture button used to represent a card in the card-hand radial menu.
    /// No additional initialization logic is performed here; styling and content are configured by the caller.
    /// </remarks>
    public CardMenuButton()
    {
    }
    public CardMenuButton()
    {

    }
}
