using Content.Client.UserInterface.Controls;
using Content.Shared.Popups;
using Content.Shared.RCD;
using Content.Shared.RCD.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client.RCD;

[GenerateTypedNameReferences]
public sealed partial class RCDMenu : RadialMenu
{
    [Dependency] private readonly EntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    private SharedPopupSystem _popup;
    private SpriteSystem _sprites;

    public event Action<ProtoId<RCDPrototype>>? SendRCDSystemMessageAction;

    private EntityUid _owner;

    /// <summary>
    /// Initializes a new RCDMenu, injecting dependencies, loading its XAML UI, and wiring runtime systems and event handlers.
    /// </summary>
    /// <remarks>
    /// Resolves the shared popup and sprite systems and subscribes to <see cref="OnChildAdded"/> so newly added radial children
    /// are wired with RCD button click actions.
    /// </remarks>
    public RCDMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _popup = _entManager.System<SharedPopupSystem>();
        _sprites = _entManager.System<SpriteSystem>();

        OnChildAdded += AddRCDMenuButtonOnClickActions;
    }

    /// <summary>
    /// Set the entity this menu represents and rebuild the menu contents for it.
    /// </summary>
    /// <param name="uid">The entity whose RCDComponent will be used to populate the menu. Can be an invalid/empty UID to clear the owner.</param>
    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
        Refresh();
    }

    /// <summary>
    /// Rebuilds the radial menu contents for the currently set owner entity.
    /// </summary>
    /// <remarks>
    /// Reads the owner's RCDComponent.AvailablePrototypes and populates the menu's category radial containers
    /// with one button per available prototype. Skips prototypes that are missing or have Mode == RcdMode.Invalid.
    /// For construct-type prototypes the button tooltip will use the linked entity prototype's display name when available.
    /// If a prototype provides a sprite, a centered TextureRect is added to its button. The method also ensures the
    /// main radial container's category-switch buttons for populated categories are made visible, and wires up click
    /// actions for each menu button.
    /// 
    /// If the owner does not have an RCDComponent, the method returns without modifying the menu.
    /// </remarks>
    public void Refresh()
    {
        // Find the main radial container
        var main = FindControl<RadialContainer>("Main");

        // Populate secondary radial containers
        if (!_entManager.TryGetComponent<RCDComponent>(_owner, out var rcd))
            return;

        foreach (var protoId in rcd.AvailablePrototypes)
        {
            if (!_protoManager.TryIndex(protoId, out var proto))
                continue;

            if (proto.Mode == RcdMode.Invalid)
                continue;

            var parent = FindControl<RadialContainer>(proto.Category);
            var tooltip = Loc.GetString(proto.SetName);

            if ((proto.Mode == RcdMode.ConstructTile || proto.Mode == RcdMode.ConstructObject) &&
                proto.Prototype != null && _protoManager.TryIndex(proto.Prototype, out var entProto, logError: false))
            {
                tooltip = Loc.GetString(entProto.Name);
            }

            tooltip = OopsConcat(char.ToUpper(tooltip[0]).ToString(), tooltip.Remove(0, 1));

            var button = new RCDMenuButton()
            {
                StyleClasses = { "RadialMenuButton" },
                SetSize = new Vector2(64f, 64f),
                ToolTip = tooltip,
                ProtoId = protoId,
            };

            if (proto.Sprite != null)
            {
                var tex = new TextureRect()
                {
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Texture = _sprites.Frame0(proto.Sprite),
                    TextureScale = new Vector2(2f, 2f),
                };

                button.AddChild(tex);
            }

            parent.AddChild(button);

            // Ensure that the button that transitions the menu to the associated category layer
            // is visible in the main radial container (as these all start with Visible = false)
            foreach (var child in main.Children)
            {
                var castChild = child as RadialMenuTextureButton;

                if (castChild is not RadialMenuTextureButton)
                    continue;

                if (castChild.TargetLayer == proto.Category)
                {
                    castChild.Visible = true;
                    break;
                }
            }
        }

        // Set up menu actions
        foreach (var child in Children)
        {
            AddRCDMenuButtonOnClickActions(child);
        }
    }

    /// <summary>
    /// Concatenates two strings using a direct runtime addition to avoid compiler optimizations that could trigger sandbox checks.
    /// </summary>
    /// <param name="a">The first string.</param>
    /// <param name="b">The second string.</param>
    /// <returns>The concatenation of <paramref name="a"/> and <paramref name="b"/>.</returns>
    private static string OopsConcat(string a, string b)
    {
        // This exists to prevent Roslyn being clever and compiling something that fails sandbox checks.
        return a + b;
    }

    /// <summary>
    /// Wires click behavior for any RCDMenuButton children of the given control.
    /// </summary>
    /// <param name="control">Expected to be a <see cref="RadialContainer"/>; non-containers are ignored.</param>
    /// <remarks>
    /// For each child that is an <see cref="RCDMenuButton"/>, subscribes to its <c>OnButtonUp</c> event.
    /// When invoked the handler:
    /// - invokes <c>SendRCDSystemMessageAction</c> with the button's <c>ProtoId</c> (if any subscribers),
    /// - if there is a local session with an attached entity and the prototype can be resolved, shows a localized
    ///   popup describing the mode or build-mode change to the attached entity,
    /// - and closes the radial menu.
    /// </remarks>
    private void AddRCDMenuButtonOnClickActions(Control control)
    {
        var radialContainer = control as RadialContainer;

        if (radialContainer == null)
            return;

        foreach (var child in radialContainer.Children)
        {
            var castChild = child as RCDMenuButton;

            if (castChild == null)
                continue;

            castChild.OnButtonUp += _ =>
            {
                SendRCDSystemMessageAction?.Invoke(castChild.ProtoId);

                if (_playerManager.LocalSession?.AttachedEntity != null &&
                    _protoManager.TryIndex(castChild.ProtoId, out var proto))
                {
                    var msg = Loc.GetString("rcd-component-change-mode", ("mode", Loc.GetString(proto.SetName)));

                    if (proto.Mode == RcdMode.ConstructTile || proto.Mode == RcdMode.ConstructObject)
                    {
                        var name = Loc.GetString(proto.SetName);

                        if (proto.Prototype != null &&
                            _protoManager.TryIndex(proto.Prototype, out var entProto, logError: false))
                            name = entProto.Name;

                        msg = Loc.GetString("rcd-component-change-build-mode", ("name", name));
                    }

                    // Popup message
                    _popup.PopupClient(msg, _owner, _playerManager.LocalSession.AttachedEntity);
                }

                Close();
            };
        }
    }
}

public sealed class RCDMenuButton : RadialMenuTextureButton
{
    public ProtoId<RCDPrototype> ProtoId { get; set; }

    /// <summary>
    /// Creates a new RCDMenuButton instance.
    /// </summary>
    public RCDMenuButton()
    {

    }
}
