// SPDX-FileCopyrightText: 2024 Emisse <99158783+Emisse@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Errant <35878406+Errant-4@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 JustCone <141039037+JustCone14@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Mervill <mervills.email@gmail.com>
// SPDX-FileCopyrightText: 2024 PJBot <pieterjan.briers+bot@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 PopGamer46 <yt1popgamer@gmail.com>
// SPDX-FileCopyrightText: 2024 Spessmann <156740760+Spessmann@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 coolboy911 <85909253+coolboy911@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 lunarcomets <140772713+lunarcomets@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 saintmuntzer <47153094+saintmuntzer@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Eoin Mcloughlin <helloworld@eoinrul.es>
// SPDX-FileCopyrightText: 2025 Fildrance <fildrance@gmail.com>
// SPDX-FileCopyrightText: 2025 pa.pecherskij <pa.pecherskij@interfax.ru>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class StationAiMenu : RadialMenu
{
    [Dependency] private readonly IClyde _clyde = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;

    public event Action<BaseStationAiAction>? OnAiRadial;

    private EntityUid _tracked;

    /// <summary>
    /// Initializes a new <see cref="StationAiMenu"/> instance.
    /// </summary>
    /// <remarks>
    /// Performs dependency injection for required services and loads the menu's XAML UI definition.
    /// </remarks>
    public StationAiMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Start tracking an entity and initialize the radial menu for its station-AI actions.
    /// </summary>
    /// <param name="owner">The entity whose AI actions should be displayed; if the entity does not exist the menu will be closed.</param>
    public void Track(EntityUid owner)
    {
        _tracked = owner;

        if (!_entManager.EntityExists(_tracked))
        {
            Close();
            return;
        }

        BuildButtons();
        UpdatePosition();
    }

    /// <summary>
    /// Populates the radial menu's "Main" container with buttons representing the tracked entity's available Station AI actions.
    /// </summary>
    /// <remarks>
    /// Raises a local <c>GetStationAiRadialEvent</c> on the currently tracked entity to obtain available actions, clears any existing children in the "Main" <c>RadialContainer</c>, and creates a <c>StationAiMenuButton</c> for each action. If an action provides a sprite, the sprite's first frame is added as a centered <c>TextureRect</c> (scaled up when small). Each button's press handler invokes <c>OnAiRadial</c> with the action's event and closes the menu. This method has the side effects of raising the local event and mutating the UI hierarchy and button event subscriptions.
    /// </remarks>
    private void BuildButtons()
    {
        var ev = new GetStationAiRadialEvent();
        _entManager.EventBus.RaiseLocalEvent(_tracked, ref ev);

        var main = FindControl<RadialContainer>("Main");
        main.DisposeAllChildren();
        var sprites = _entManager.System<SpriteSystem>();

        foreach (var action in ev.Actions)
        {
            // TODO: This radial boilerplate is quite annoying
            var button = new StationAiMenuButton(action.Event)
            {
                StyleClasses = { "RadialMenuButton" },
                SetSize = new Vector2(64f, 64f),
                ToolTip = action.Tooltip != null ? Loc.GetString(action.Tooltip) : null,
            };

            if (action.Sprite != null)
            {
                var texture = sprites.Frame0(action.Sprite);
                var scale = Vector2.One;

                if (texture.Width <= 32)
                {
                    scale *= 2;
                }

                var tex = new TextureRect
                {
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Texture = texture,
                    TextureScale = scale,
                };

                button.AddChild(tex);
            }

            button.OnPressed += args =>
            {
                OnAiRadial?.Invoke(action.Event);
                Close();
            };
            main.AddChild(button);
        }
    }

    /// <summary>
    /// Called once per frame; runs base frame update logic and refreshes the menu's screen position.
    /// </summary>
    /// <param name="args">Frame timing information for the current frame.</param>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdatePosition();
    }

    /// <summary>
    /// Repositions the radial menu to follow the currently tracked entity on screen.
    /// </summary>
    /// <remarks>
    /// Attempts to resolve the tracked entity's transform and compute its sprite screen coordinates.
    /// If the entity, its coordinates, or the computed screen coordinates are invalid, the menu is closed.
    /// On success, opens the menu at the computed screen position using the injected Clyde instance.
    /// </remarks>
    private void UpdatePosition()
    {
        if (!_entManager.TryGetComponent(_tracked, out TransformComponent? xform))
        {
            Close();
            return;
        }

        if (!xform.Coordinates.IsValid(_entManager))
        {
            Close();
            return;
        }

        var coords = _entManager.System<SpriteSystem>().GetSpriteScreenCoordinates((_tracked, null, xform));

        if (!coords.IsValid)
        {
            Close();
            return;
        }

        OpenScreenAt(coords.Position, _clyde);
    }
}

public sealed class StationAiMenuButton(BaseStationAiAction action) : RadialMenuTextureButton
{
    public BaseStationAiAction Action = action;
}
